### ISSUE TITLE
Misleading error message for invalid annotation format

### ISSUE THREAD

**Issue by lewyg** [crossplane-contrib/function-go-templating#46]
### What happened?

When adding annotation to make resource ready (based on README example):

```yaml
 gotemplating.fn.crossplane.io/ready: True
```

I am getting an error:

```
crossplane: error: cannot render composite resource: pipeline step "render-templates" returned a fatal result: "User" template is missing required "gotemplating.fn.crossplane.io/composition-resource-name" annotation
```

This is misleading because I have set`gotemplating.fn.crossplane.io/composition-resource-name` annotation, and the real error is caused by an invalid format of `ready` annotation (boolean instead of string). It works when I change it to:

```yaml
 gotemplating.fn.crossplane.io/ready: "True"
```

### What environment did it happen in?
Function version: 0.3.0

**Comment by dee-kryvenko** [comment]
Just ran into this issue as well... title README.md is misleading, and this error message makes it even harder to pinpoint. Dunno how many hours I would wasted if you didn't create this issue @lewyg - thanks

**Comment by jtucci** [comment]
What's happening here is that the YAML decoder will interpret unquoted True or False values as a boolean true or false. 

ex 
When setting the following in a composition 
```go
apiVersion: example.crossplane.io/v1beta1
kind: Example
metadata:
  annotations:
     gotemplating.fn.crossplane.io/ready: True
     crossplane.io/composition-resource-name: example
```

and output the unmarshaled object you will see 

```yaml
{Object:map[apiVersion:apiVersion: example.crossplane.io/v1beta1 kind:Example metadata:map[annotations:map[gotemplating.fn.crossplane.io/ready:false crossplane.io/composition-resource-name: example]] }
```
This conversion is problematic when such annotations are expected to be strings, as demonstrated in the following snippet:
Later in  `RunFunction` you see 
```go
name, found := obj.GetAnnotations()[annotationKeyCompositionResourceName]
if !found {
	response.Fatal(rsp, errors.Errorf("%q template is missing required %q annotation", obj.GetKind(), annotationKeyCompositionResourceName))
	return rsp, nil
}
```

GetAnnotations will internally call `NestedStringMap `. In this case, it will hit the not ok condition and return an error. 
```go
func NestedStringMap(obj map[string]interface{}, fields ...string) (map[string]string, bool, error) {
        ....
	for k, v := range m {
		if str, ok := v.(string); ok {
			strMap[k] = str
		} else {
			return nil, false, fmt.Errorf("%v accessor error: contains non-string key in the map: %v is of the type %T, expected string", jsonPath(fields), v, v)
		}
	}
	....
```

Since GetAnnotations ignores the returned errors, we end up with a nil map which results in the  `template is missing required annotation` error.
